import { create } from "zustand";
import { persist } from "zustand/middleware";

export interface FileSystemNode {
  id: string;
  name: string;
  type: "file" | "directory";
  content?: string;
  children?: FileSystemNode[];
  parentId?: string;
}

export interface NginxConfig {
  raw: string;
  ast: unknown;
}

export interface SyntaxError {
  line: number;
  column: number;
  message: string;
}

export interface SecurityAuditResult {
  id: string;
  severity: "critical" | "warning" | "info";
  message: string;
  directive?: string;
}

export type TabType = "ui" | "code" | "visual" | "analytics";

interface AppState {
  // File System State
  fileSystem: FileSystemNode[];
  activeFileId: string | null;

  // Configuration State
  rawConfig: string;
  parsedConfig: NginxConfig | null;

  // UI State
  activeTab: TabType;
  sidebarCollapsed: boolean;
  isInitialized: boolean;

  // File tree UI preferences (persisted)
  sidebarSizePct: number; // percentage (0–100) of the panel group width
  expandedDirs: string[]; // array of expanded directory IDs

  // Parse Results
  syntaxErrors: SyntaxError[];
  securityAudits: SecurityAuditResult[];
  healthScore: number;

  // Actions
  initializeWorkspace: (files?: FileSystemNode[]) => void;
  importFiles: (files: FileList) => void;
  createNewConfig: () => void;
  selectFile: (fileId: string) => void;
  updateConfig: (content: string) => void;
  switchTab: (tab: TabType) => void;
  toggleSidebar: () => void;
  setSidebarSizePct: (pct: number) => void;
  setExpandedDirs: (dirs: string[]) => void;
  resetWorkspace: () => void;
  setParsedConfig: (config: NginxConfig | null) => void;
  setSyntaxErrors: (errors: SyntaxError[]) => void;
  setSecurityAudits: (audits: SecurityAuditResult[]) => void;
  setHealthScore: (score: number) => void;
}

export const useAppStore = create<AppState>()(
  persist(
    (set, get) => ({
      // Initial State
      fileSystem: [],
      activeFileId: null,
      rawConfig: "",
      parsedConfig: null,
      activeTab: "ui",
      sidebarCollapsed: false,
      isInitialized: false,
      sidebarSizePct: 20,
      expandedDirs: ["/etc/nginx"],
      syntaxErrors: [],
      securityAudits: [],
      healthScore: 0,

      // Actions
      initializeWorkspace: (files = []) => {
        set({
          fileSystem: files.length > 0 ? files : getDefaultFileSystem(),
          isInitialized: true,
          activeFileId:
            files.length > 0 ? files[0]?.id : "/etc/nginx/nginx.conf",
        });
      },

      importFiles: (files: FileList) => {
        Array.from(files).forEach((file) => {
          const reader = new FileReader();
          reader.onload = (e) => {
            const content = e.target?.result as string;
            const node: FileSystemNode = {
              id: `/etc/nginx/${file.name}`,
              name: file.name,
              type: "file",
              content,
              parentId: "/etc/nginx",
            };
            set((state) => ({
              fileSystem: [...state.fileSystem, node],
              isInitialized: true,
            }));
          };
          reader.readAsText(file);
        });
      },

      createNewConfig: () => {
        const defaultNginxConf = `# Nginx Configuration File
# Generated by Nginx Config Visualizer

worker_processes auto;
worker_rlimit_nofile 65535;

events {
    worker_connections 4096;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml+rss application/json;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}`;

        const nginxFile: FileSystemNode = {
          id: "/etc/nginx/nginx.conf",
          name: "nginx.conf",
          type: "file",
          content: defaultNginxConf,
          parentId: "/etc/nginx",
        };

        const rootDir: FileSystemNode = {
          id: "/etc/nginx",
          name: "nginx",
          type: "directory",
          children: [nginxFile],
          parentId: undefined,
        };

        set({
          fileSystem: [rootDir],
          isInitialized: true,
          activeFileId: "/etc/nginx/nginx.conf",
          rawConfig: defaultNginxConf,
          expandedDirs: ["/etc/nginx"],
        });
      },

      selectFile: (fileId: string) => {
        // Search recursively through the file system tree
        const findFile = (
          nodes: FileSystemNode[]
        ): FileSystemNode | undefined => {
          for (const node of nodes) {
            if (node.id === fileId) return node;
            if (node.children) {
              const found = findFile(node.children);
              if (found) return found;
            }
          }
        };
        const file = findFile(get().fileSystem);
        if (file && file.type === "file") {
          set({ activeFileId: fileId, rawConfig: file.content || "" });
        }
      },

      updateConfig: (content: string) => {
        const updateNode = (
          nodes: FileSystemNode[],
          targetId: string
        ): FileSystemNode[] =>
          nodes.map((node) => {
            if (node.id === targetId) return { ...node, content };
            if (node.children)
              return { ...node, children: updateNode(node.children, targetId) };
            return node;
          });
        set((state) => ({
          rawConfig: content,
          fileSystem: state.activeFileId
            ? updateNode(state.fileSystem, state.activeFileId)
            : state.fileSystem,
        }));
      },

      switchTab: (tab: TabType) => set({ activeTab: tab }),

      toggleSidebar: () =>
        set((state) => ({ sidebarCollapsed: !state.sidebarCollapsed })),

      setSidebarSizePct: (pct: number) => set({ sidebarSizePct: pct }),

      setExpandedDirs: (dirs: string[]) => set({ expandedDirs: dirs }),

      resetWorkspace: () => {
        set({
          fileSystem: [],
          activeFileId: null,
          rawConfig: "",
          parsedConfig: null,
          activeTab: "ui",
          sidebarCollapsed: false,
          isInitialized: false,
          expandedDirs: ["/etc/nginx"],
          syntaxErrors: [],
          securityAudits: [],
          healthScore: 0,
        });
      },

      setParsedConfig: (config) => set({ parsedConfig: config }),
      setSyntaxErrors: (errors) => set({ syntaxErrors: errors }),
      setSecurityAudits: (audits) => set({ securityAudits: audits }),
      setHealthScore: (score) => set({ healthScore: score }),
    }),
    {
      name: "nginx-visualizer-storage",
      partialize: (state) => ({
        fileSystem: state.fileSystem,
        activeFileId: state.activeFileId,
        rawConfig: state.rawConfig,
        activeTab: state.activeTab,
        sidebarCollapsed: state.sidebarCollapsed,
        isInitialized: state.isInitialized,
        sidebarSizePct: state.sidebarSizePct,
        expandedDirs: state.expandedDirs,
      }),
    }
  )
);

function getDefaultFileSystem(): FileSystemNode[] {
  return [
    {
      id: "/etc/nginx",
      name: "nginx",
      type: "directory",
      children: [
        {
          id: "/etc/nginx/nginx.conf",
          name: "nginx.conf",
          type: "file",
          content: "",
          parentId: "/etc/nginx",
        },
      ],
      parentId: undefined,
    },
  ];
}
