import { Editor } from "@monaco-editor/react";
import { useState } from "react";

const defaultNginxConfig = `# Nginx configuration file
# Generated by Nginx Config Visualizer

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}`;

export function CodeConfigPage() {
  const [code, setCode] = useState(defaultNginxConfig);
  const [isValid] = useState(true);

  const handleEditorChange = (value: string | undefined) => {
    setCode(value || "");
  };

  return (
    <div className="flex-1 overflow-hidden flex flex-col bg-background-base">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-6 py-3 border-b border-outline-variant bg-surface-container-low shrink-0">
        <div className="flex items-center gap-3">
          <span className="text-label-caps text-on-surface-variant uppercase">
            nginx.conf
          </span>
          <span
            className={`px-2 py-0.5 rounded text-[10px] border ${
              isValid
                ? "bg-accent-active/10 text-accent-active border-accent-active/20"
                : "bg-accent-error/10 text-accent-error border-accent-error/20"
            }`}
          >
            {isValid ? "Valid" : "Invalid"}
          </span>
        </div>
        <div className="flex items-center gap-2">
          <button className="px-3 py-1.5 rounded-lg border border-outline-variant text-body-sm text-on-surface-variant hover:bg-surface-variant transition-colors">
            Format
          </button>
          <button className="px-3 py-1.5 rounded-lg bg-primary text-on-primary text-body-sm font-bold hover:opacity-90 transition-opacity">
            Save
          </button>
        </div>
      </div>

      {/* Editor */}
      <div className="flex-1">
        <Editor
          height="100%"
          language="nginx"
          value={code}
          onChange={handleEditorChange}
          theme="vs-dark"
          options={{
            fontSize: 14,
            fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
            lineHeight: 1.6,
            automaticLayout: true,
            minimap: { enabled: false },
            scrollBeyondLastLine: false,
            wordWrap: "on",
            renderWhitespace: "boundary",
            bracketPairColorization: { enabled: true },
            guides: {
              indentation: true,
            },
          }}
        />
      </div>
    </div>
  );
}